# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-09-20 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('addr', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
